# **UTP AI**

*   **Nama**  : Tasya Azzahra Putri
*   **NPM**   : 2117051043
*   **Kelas** : C

**Sumber Dataset** : https://data.world/data-society/iris-species

## **Library**

In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

## **Load Data**

In [ ]:
# Load data dari Github

dataset = pd.read_csv("https://raw.githubusercontent.com/tasyaazzahraputri/UTP_AI/main/Iris.csv")
dataset

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

## **Preprocessing**

In [ ]:
# data cleaning
dataset = dataset.dropna()
dataset = dataset.drop(["Id"], axis = 1)
dataset

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# type conversion
dataset.loc [dataset['Species'] == 'Iris-setosa', 'Species'] = '1'
dataset.loc [dataset['Species'] == 'Iris-versicolor', 'Species'] = '2'
dataset.loc [dataset['Species'] == 'Iris-virginica', 'Species'] = '3'
dataset

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0              5.1           3.5            1.4           0.2       1
1              4.9           3.0            1.4           0.2       1
2              4.7           3.2            1.3           0.2       1
3              4.6           3.1            1.5           0.2       1
4              5.0           3.6            1.4           0.2       1
..             ...           ...            ...           ...     ...
145            6.7           3.0            5.2           2.3       3
146            6.3           2.5            5.0           1.9       3
147            6.5           3.0            5.2           2.0       3
148            6.2           3.4            5.4           2.3       3
149            5.9           3.0            5.1           1.8       3

[150 rows x 5 columns]

## **Splitting Data**

In [ ]:
data_train, data_test = train_test_split(dataset, train_size = 0.8, random_state = 65)

In [ ]:
X_train = data_train.drop('Species', axis=1)
y_train = data_train['Species']
X_test = data_test.drop('Species', axis=1)
y_test = data_test['Species']

In [ ]:
# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## **Model**

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

## **Evaluasi**

In [ ]:
akurasi = model.score(X_test, y_test)
akurasi

0.8666666666666667

## **Prediksi Data Dummy**

In [ ]:
dummy = pd.read_csv("https://raw.githubusercontent.com/tasyaazzahraputri/UTP_AI/main/data_dummy.csv")
dummy

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            4.9           3.1            1.5           0.1
1            6.8           2.8            4.8           1.4
2            6.4           3.1            5.5           1.8
3            6.0           3.4            4.5           1.6
4            5.1           3.4            1.5           0.2

In [ ]:
prediksi_spesies = model.predict(dummy.values)
dummy["Spesies"] = prediksi_spesies
dummy

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Spesies
0            4.9           3.1            1.5           0.1       2
1            6.8           2.8            4.8           1.4       3
2            6.4           3.1            5.5           1.8       3
3            6.0           3.4            4.5           1.6       3
4            5.1           3.4            1.5           0.2       2